on:
  release:
    types: [published]

name: Build Release
jobs:
  make:
    name: Build and Upload Sileo
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          submodules: recursive

      - name: Setup Procursus Bootstrap (install)
        run: |
          wget https://apt.procurs.us/bootstraps/big_sur/bootstrap-darwin-arm64.tar.zst
          sudo gtar --preserve-permissions -xkf ./bootstrap-darwin-arm64.tar.zst -C /
          echo '/opt/procursus/sbin:/opt/procursus/bin' >> $GITHUB_PATH
          PATH=/opt/procursus/sbin:/opt/procursus/bin:$PATH sudo /opt/procursus/bin/apt update
          sudo /opt/procursus/bin/apt -V full-upgrade -y --allow-downgrades -oDpkg::Options::=--force-confdef -oDpkg::Options::=--force-confnew 
        continue-on-error: true
      
      - name: Upgrade
        run: |
          sudo /opt/procursus/bin/apt -V upgrade -y --allow-downgrades -oDpkg::Options::=--force-confdef -oDpkg::Options::=--force-confnew
    
      - name: Upgrade and install
        run: |
          sudo /opt/procursus/bin/apt install zstd apt-utils ldid xz-utils bzip2 lz4 -y --allow-downgrades -oDpkg::Options::=--force-confdef -oDpkg::Options::=--force-confnew
        
      - name: Add Procursus to PATH
        run: |
          echo '/opt/procursus/sbin:/opt/procursus/bin' >> $GITHUB_PATH

      - name: Select Correct Xcode (16.4)
        run: |
          sudo xcode-select --switch /Applications/Xcode_16.4.app

      - name: Build Sileo (iphoneos-arm)
        run: |
          make clean package DEBUG=0 ALL_BOOTSTRAPS=1 SILEO_PLATFORM=iphoneos-arm

      - name: Build Sileo (iphoneos-arm64)
        run: |
          make clean package DEBUG=0 ALL_BOOTSTRAPS=1 SILEO_PLATFORM=iphoneos-arm64

      - name: Upload Sileo (iphoneos-arm)
        uses: actions/upload-artifact@v4
        with:
            name: org.coolstar.sileo_iphoneos-arm
            path: ./packages/*_iphoneos-arm.deb
  
      - name: Upload Sileo (iphoneos-arm64)
        uses: actions/upload-artifact@v4
        with:
            name: org.coolstar.sileo_iphoneos-arm64
            path: ./packages/*_iphoneos-arm64.deb